### ISSUE TITLE
Pypi integration on build

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#10]
- [ ] The azure build tools needs to be updated to create a new pypi package deepforest_pytorch.

**Comment by bw4sz** [comment]
Building azure pipelines here, it will fail at first and then can debug 

https://dev.azure.com/benweinstein2010/DeepForest/_build

**Comment by bw4sz** [comment]
Creating first release for azure to build on tags and pull requests https://dev.azure.com/benweinstein2010/DeepForest/_releaseProgress?_a=release-environment-logs&releaseId=94&environmentId=177

**Comment by bw4sz** [comment]
Pypi build pushed.

https://pypi.org/project/deepforest-pytorch/

not quite right though. Pip install works fine.

```
pip install deepforest-pytorch
```

But the syntax isn't totally correct, you can load 'deepforest' module but not the deepforest package? Not sure I've got the right terminology. Something about the setup.py isn't quite right.
```
(test) benweinstein@Bens-MacBook-Pro NeonTreeEvaluation % python
Python 3.8.5 (default, Sep  4 2020, 02:22:02)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from deepforest import deepforest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'deepforest' from 'deepforest' (unknown location)
```

But asking for the module directly works.
```
>>> import deepforest
>>>
```

Its also not
```
>>> from deepforest_pytorch import deepforest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'deepforest_pytorch'
```

Maybe need to define an entry point? We want to python module to be named deepforest, but pip install to distinguish between deepforest-pytorch and the original?

@henrykironde do you know the answer to this?

**Comment by henrykironde** [comment]
Checking it out right now

**Comment by henrykironde** [comment]
It should be `from deepforest import ........`

**Comment by henrykironde** [comment]
Example usage
```Python
>>> from deepforest import *
>>> from deepforest import training
>>> from deepforest import preprocess
```

**Comment by bw4sz** [comment]
ugh! obviously. I had renamed deepforest/deepforest.py -> deepforest/main.py and forgot between versions. Sorry.
