### ISSUE TITLE
Load and save models

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#15]
main.py needs a way to save a trained model and then reload model method for recreating deepforest instances. test should confirm that prediction before and after should yield the same results.

@dingyif if you are interested, this seems like a good place to help. No pressure.

**Comment by dingyif** [comment]
Definitely, I will take a look at it.

**Comment by bw4sz** [comment]
Hold off here for a couple days. I'm playing with integrating the trainer into pytorch-lightning to gain access to these kind of convenience structures and logging.

**Comment by bw4sz** [comment]
Okay https://github.com/weecology/DeepForest-pytorch/commit/5b371f6084ac58fb7f42c301fa134583bb2c73f7 , makes the main module a pytorch-lightning object. deepforest.save() and deepforest.load() should look like something here https://pytorch-lightning.readthedocs.io/en/stable/weights_loading.html

The load saved model under __init__

```
        if saved_model:
            utilities.load_saved_model(saved_model)
```

probably is now not that logical and could be removed. Probably better to load the entire pytorch-lightning module and all of its functionality. 

Inching towards first stable version. I'm working on a couple callbacks and will retrain the deepforest release model.

**Comment by dingyif** [comment]
https://pytorch-lightning.readthedocs.io/en/0.7.0/weights_loading.html

Is this something we should implement?

**Comment by dingyif** [comment]
I was writing the test case for the new method I created. 
I have some questions, please pardon me if I'm being stupid in those questions.

1. For the m function  why we're using `m.model = model.load_backbone()` instead of `m.create_model()` since you already create `m.create_model()` method in deepforest module. 
2. Do you have problems with the `predict_tile` method?  It feels for me, there's no prediction result for that one.

**Comment by bw4sz** [comment]
Those two questions are related! Because we have no release model yet, the random model is just randomly initialized weights. So it happens to not predict any trees in that data, so the test fails. Once we have a release model, don't need to bother with model.load_backbone(), we will have .use_release() method just like in the other package. I have models running right now, but they aren't quite right.

![WREF_083_step_1109](https://user-images.githubusercontent.com/1208492/109722225-43889200-7b61-11eb-9129-528aef0a4735.png)
something is wrong with hyperparameters. When we go to 0.2.0 there will be a release model to use for all tests. Right now it is a bit weird, applying the pretrained COCO model from pytorch vision on tree images from the sample data. Its just a workaround.

For loading and saving I tried https://github.com/weecology/DeepForest_Model/blob/c91989748ed83b02ab44ce6fbb6cadb819028d59/train.py#L39
not pretty, but gets it done for the moment.

**Comment by dingyif** [comment]
Great! I will change that `m.create_model()` back to `m.model = model.load_backbone()` right now.

Do you want to integrate the method created related to this issue? You can just use `m.save_model(path)` to save the model_checkpoint.

Sorry about the late commit. It was really a long week.
