### ISSUE TITLE
Evaluate module not in docs.

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#31]
@henrykironde do you have a second to guess at something?

The evaluate module is a blank page sitting on its own outside of deepforest package. At the same time there is no evaluate submodule in package source docs. There should be deepforest.evaluate submodule alongside all the others. Sphinx does not throw any flags. I didn't check readthedocs logs.

https://github.com/weecology/DeepForest-pytorch/blob/master/deepforest/evaluate.py

https://deepforest-pytorch.readthedocs.io/en/latest/source/deepforest.html

Looking at readthedocs, you can see 
<img width="347" alt="Screen Shot 2021-03-15 at 2 01 25 PM" src="https://user-images.githubusercontent.com/1208492/111221386-a9c8d800-8597-11eb-8b19-7d9c0e72bbff.png">

I've tried deleting those files and recreating.

```
cd /Users/benweinstein/Documents/DeepForest-pytorch/docs
sphinx-apidoc -o source ../
```

but no change. 
latest commit 86a6a3129f68c66bc74774f20542c27f7c96a930

**Comment by henrykironde** [comment]
The main part was to install the current changes before running make html.
I have done some cleaning of the docs to reduce the warnings. 4 warnings are still present but they are due to the package tqdm. We cannot avoid them.
