### ISSUE TITLE
Build Wheel Error

### ISSUE THREAD

**Issue by dwaipayan05** [weecology/DeepForest-pytorch#34]
While running `pip install -r dev_requirements.txt` inside my virtual environment the following error occurred

![image](https://user-images.githubusercontent.com/53687927/111526308-962e9480-8784-11eb-8505-ece60e847864.png)

System Specifications

- Python - 3.8.7
- OS - Windows 10 Home Single Language

**Comment by bw4sz** [comment]
This is upstream of this library and specific to your build. I recommend conda environments as pip + rasterio + gdal is for more experienced users, especially on windows. Check out the rasterio help installation if you want to pip install.
