### ISSUE TITLE
utilities.shapefile_to_annotations  won't save csv

### ISSUE THREAD

**Issue by dingyif** [weecology/DeepForest-pytorch#43]
Need to add the below code, in the end, will commit this after the previous commit merged successfully. 

```
#save the data frame to CSV file at the specific location
    result.to_csv(os.path.join(savedir,'annotations.csv'),index=False)
```

**Comment by bw4sz** [comment]
Is there a reason to do this inside the function? Rather than just the function returning the result dataframe and they can choose to save it? I'm open either way.

**Comment by dingyif** [comment]
I see. From the documentation of the function, it says it will give the path and save it. I thought you miss that line. No worries.
