### ISSUE TITLE
What happened to the sphinx documentation?

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#49]
All the sources docs are not being built. Clearly a sphinx error. @henrykironde if you around and want to look, if not i'll try to see this afternoon. I bet it has something to do with mocking sphinx dependencies. I got myself into trouble here on readthedocs

https://github.com/weecology/DeepForest-pytorch/blob/7db4cc12213d80892327d350508e50fc837ab94d/docs/conf.py#L96

https://deepforest-pytorch.readthedocs.io/en/latest/source/deepforest.html#submodules

**Comment by henrykironde** [comment]
Why do we need to mock the imports?

**Comment by bw4sz** [comment]
I was getting many errors on read the docs trying to install source. 
https://docs.readthedocs.io/en/stable/config-file/v2.html

```

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
```

https://readthedocs.org/projects/deepforest-pytorch/builds/13385581/
if you look at the readthedoc builds you'll see lots of errors. So i decided to mock it. Which passed, but now the html doesn't build, which I guess should have been obvious.

**Comment by henrykironde** [comment]
@bw4sz it seems that you need to change the version of pillow.

I have tried to use mock, but that library will not create good docs. Also we had to include mock in the requirements. Even with that approach, I couldn't get the docs to run correct.

This seems to have solved the issue
