### ISSUE TITLE
How can box recall and class recall be different when num_class=1

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest-pytorch#58]

**Comment by bw4sz** [comment]
![Uploading Screen Shot 2021-04-15 at 2.16.42 PM.png…]()

**Comment by henrykironde** [comment]
@bw4sz Could you upload the image again

**Comment by bw4sz** [comment]
https://www.comet.ml/bw4sz/everglades/view/oVLfVkOc3LO36UBsTHnl030At

This needs some clear information in the docs.

**Comment by bw4sz** [comment]
Corrected, the precision was being calculated on all boxes, but recall was just the class-matching boxes.
